### ISSUE TITLE
"missing which project it belongs to"  error when running mergin_db_sync docker container

### ISSUE THREAD

**Issue by HugoP27** [lutraconsulting/mergin-db-sync#40]
Hi
I've built the container from dockerhub, but after it initializes I get the following issue:

![image](https://user-images.githubusercontent.com/51097011/115390888-16f70b00-a1df-11eb-807e-791ade4d4111.png)

** Please note I use the --init-from-gpkg flag and not --init-from-db

**Comment by wonder-sk** [comment]
You probably have the base/modified schemas in your database from previous versions of mergin-db-sync... To make db-sync more robust, we are now adding extra metadata to those base/modified schemas when we newly create them. As a fix, could you please drop those existing schemas before you start the container? Afterwards, this error should not pop up anymore...

**Comment by HugoP27** [comment]
I tried it, but it still throws the same error. I created a short screen recording to show what it does:

[screenrecording](https://youtu.be/cp-Oz_RLbcE)

**Comment by HugoP27** [comment]
hi @wonder-sk, I will email you the dataset. no problem, thank you.

**Comment by wonder-sk** [comment]
Thanks, there are two problems - the first one will be fixed with https://github.com/lutraconsulting/geodiff/pull/110 and the second one is another instance of https://github.com/lutraconsulting/geodiff/issues/107 which we will look into as well

**Comment by wonder-sk** [comment]
The second problem should be fixed with https://github.com/lutraconsulting/geodiff/pull/112

**Comment by wonder-sk** [comment]
All the issues should be fixed now in the 1.0.3 release... A new docker container is available.

**Comment by HugoP27** [comment]
Hi @wonder-sk , just confirming that this issue still persists
